name:                sd-jwt
version:             0.1.0.0
github:              "yaronf/sd-jwt"
license:             BSD3
author:              "Yaron Sheffer"
maintainer:          "yaronf.ietf@gmail.com"
copyright:           "2025 Yaron Sheffer"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
synopsis:            "Selective Disclosure for JSON Web Tokens (RFC 9901)"
description:         "Implementation of RFC 9901: Selective Disclosure for JSON Web Tokens (SD-JWT)"
category:            Web

dependencies:
- base >= 4.14 && < 5
- aeson >= 2.0
- bytestring >= 0.11
- text >= 2.0
- cryptonite >= 0.30  # Still needed for hashing and random number generation
- memory >= 0.18  # Required by cryptonite
- jose >= 0.10  # JWT/JWS library with EC signing support and native typ header support (replaces jose-jwt)
- lens >= 4.16  # Required by jose for header manipulation
- base64-bytestring >= 1.2
- containers >= 0.6
- vector >= 0.13

ghc-options:
- -Wall                    # Enable all standard warnings
- -Wcompat                 # Warn about compatibility issues
- -Widentities             # Warn about redundant identity functions
- -Wincomplete-record-updates # Warn about incomplete record updates
- -Wincomplete-uni-patterns # Warn about incomplete pattern matches
- -Wmissing-export-lists   # Warn about missing export lists
- -Wmissing-home-modules   # Warn about missing home modules
- -Wpartial-fields         # Warn about partial record fields
- -Wredundant-constraints  # Warn about redundant constraints
- -Wunused-packages        # Warn about unused packages
- -Wmissing-deriving-strategies # Warn about missing deriving strategies
- -Wno-missing-import-lists   # Disable: (..) imports are acceptable for constructors
- -Wno-unused-imports      # Disable: unused imports are acceptable (often used for re-exports or future use)
- -Wunused-type-patterns   # Warn about unused type patterns
- -Wunused-record-wildcards # Warn about unused record wildcards
- -Wredundant-record-wildcards # Warn about redundant record wildcards
- -Wtype-defaults          # Warn about type defaulting
- -Wunused-do-bind         # Warn about unused do bindings
- -Wunused-foralls          # Warn about unused foralls
- -Wdeprecations            # Warn about deprecated functions
- -Wnoncanonical-monad-instances # Warn about non-canonical monad instances

library:
  source-dirs: src
  exposed-modules:
    # Main entry points - use these for most use cases
    - SDJWT.Issuer    # For creating and issuing SD-JWTs
    - SDJWT.Holder    # For receiving SD-JWTs and creating presentations
    - SDJWT.Verifier  # For verifying SD-JWT presentations
    # Internal submodules - low-level/internal use
    - SDJWT.Internal.Types
    - SDJWT.Internal.Utils
    - SDJWT.Internal.Digest
    - SDJWT.Internal.Disclosure
    - SDJWT.Internal.Serialization
    - SDJWT.Internal.Issuance
    - SDJWT.Internal.Presentation
    - SDJWT.Internal.Verification
    - SDJWT.Internal.KeyBinding
    - SDJWT.Internal.JWT
    # Main module - convenience re-export of persona modules
    - SDJWT           # Re-exports Issuer, Holder, Verifier

executables:
  sd-jwt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sd-jwt

tests:
  sd-jwt-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - UtilsSpec
    - DigestSpec
    - DisclosureSpec
    - SerializationSpec
    - IssuanceSpec
    - PresentationSpec
    - VerificationSpec
    - KeyBindingSpec
    - JWTSpec
    - RFCSpec
    - PropertySpec
    - EndToEndSpec
    - TestHelpers
    - TestKeys
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sd-jwt
    - hspec >= 2.10
    - QuickCheck >= 2.14
