name:                sd-jwt
version:             0.1.0.0
github:              "yaronf/sd-jwt"
license:             BSD3
author:              "Yaron Sheffer"
maintainer:          "yaronf.ietf@gmail.com"
copyright:           "2025 Yaron Sheffer"

flags:
  interop-tests:
    description: Build interoperability test executable (not built by default)
    default: False
    manual: True

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
synopsis:            "Selective Disclosure for JSON Web Tokens (RFC 9901)"
description:         "Implementation of RFC 9901: Selective Disclosure for JSON Web Tokens (SD-JWT)"
category:            Web

dependencies:
- base >= 4.14 && < 5
- aeson >= 2.0 && < 2.3
- bytestring >= 0.11 && < 0.12
- text >= 2.0 && < 2.1
- cryptonite >= 0.30 && < 0.31
- memory >= 0.18 && < 0.19
- jose >= 0.10 && < 0.13
- lens >= 4.16 && < 5.4
- base64-bytestring >= 1.2 && < 1.3
- containers >= 0.6 && < 0.7
- vector >= 0.13 && < 0.14
- time >= 1.9 && < 1.13
- scientific >= 0.3 && < 0.4

ghc-options:
- -Wall                    # Enable all standard warnings
- -Wcompat                 # Warn about compatibility issues
- -Widentities             # Warn about redundant identity functions
- -Wincomplete-record-updates # Warn about incomplete record updates
- -Wincomplete-uni-patterns # Warn about incomplete pattern matches
- -Wmissing-export-lists   # Warn about missing export lists
- -Wmissing-home-modules   # Warn about missing home modules
- -Wpartial-fields         # Warn about partial record fields
- -Wredundant-constraints  # Warn about redundant constraints
- -Wunused-packages        # Warn about unused packages
- -Wmissing-deriving-strategies # Warn about missing deriving strategies
- -Wno-missing-import-lists   # Disable: (..) imports are acceptable for constructors
- -Wno-unused-imports      # Disable: unused imports are acceptable (often used for re-exports or future use)
- -Wunused-type-patterns   # Warn about unused type patterns
- -Wunused-record-wildcards # Warn about unused record wildcards
- -Wredundant-record-wildcards # Warn about redundant record wildcards
- -Wtype-defaults          # Warn about type defaulting
- -Wunused-do-bind         # Warn about unused do bindings
- -Wunused-foralls          # Warn about unused foralls
- -Wdeprecations            # Warn about deprecated functions
- -Wnoncanonical-monad-instances # Warn about non-canonical monad instances

library:
  source-dirs: src
  exposed-modules:
    # Main entry points - use these for most use cases
    - SDJWT.Issuer    # For creating and issuing SD-JWTs
    - SDJWT.Holder    # For receiving SD-JWTs and creating presentations
    - SDJWT.Verifier  # For verifying SD-JWT presentations
    # Internal submodules - low-level/internal use
    - SDJWT.Internal.Types
    - SDJWT.Internal.Utils
    - SDJWT.Internal.Digest
    - SDJWT.Internal.Disclosure
    - SDJWT.Internal.Serialization
    - SDJWT.Internal.Issuance
    - SDJWT.Internal.Presentation
    - SDJWT.Internal.Verification
    - SDJWT.Internal.KeyBinding
    - SDJWT.Internal.JWT
    # Main module - convenience re-export of persona modules
    - SDJWT           # Re-exports Issuer, Holder, Verifier

tests:
  sd-jwt-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - UtilsSpec
    - DigestSpec
    - DisclosureSpec
    - SerializationSpec
    - IssuanceSpec
    - PresentationSpec
    - VerificationSpec
    - KeyBindingSpec
    - JWTSpec
    - RFCSpec
    - InteropFailureAnalysisSpec
    - PropertySpec
    - EndToEndSpec
    - DoctestSpec
    - ExampleSpec
    - TestHelpers
    - TestKeys
    ghc-options:
    - -Wall                    # Enable all standard warnings
    - -Wcompat                 # Warn about compatibility issues
    - -Widentities             # Warn about redundant identity functions
    - -Wincomplete-record-updates # Warn about incomplete record updates
    - -Wincomplete-uni-patterns # Warn about incomplete pattern matches
    - -Wmissing-export-lists   # Warn about missing export lists
    - -Wmissing-home-modules   # Warn about missing home modules
    - -Wpartial-fields         # Warn about partial record fields
    - -Wredundant-constraints  # Warn about redundant constraints
    - -Wunused-packages        # Warn about unused packages
    - -Wmissing-deriving-strategies # Warn about missing deriving strategies
    - -Wno-missing-import-lists   # Disable: (..) imports are acceptable for constructors
    - -Wno-unused-imports      # Disable: unused imports are acceptable (often used for re-exports or future use)
    - -Wunused-type-patterns   # Warn about unused type patterns
    - -Wunused-record-wildcards # Warn about unused record wildcards
    - -Wredundant-record-wildcards # Warn about redundant record wildcards
    - -Wtype-defaults          # Warn about type defaulting
    - -Wunused-do-bind         # Warn about unused do bindings
    - -Wunused-foralls          # Warn about unused foralls
    - -Wdeprecations            # Warn about deprecated functions
    - -Wnoncanonical-monad-instances # Warn about non-canonical monad instances
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sd-jwt
    - hspec >= 2.10
    - QuickCheck >= 2.14
    - markdown-unlit >= 0.5
    - doctest >= 0.22
    - process >= 1.6
    - filepath >= 1.4
    - directory >= 1.3
    - time >= 1.9

executables:
  sd-jwt-example:
    main:                examples/EndToEndExample.hs
    source-dirs:         .
    ghc-options:
    - -Wno-unused-packages
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sd-jwt
    - aeson >= 2.0 && < 2.3
    - bytestring >= 0.11 && < 0.12
    - containers >= 0.6 && < 0.7
    - directory >= 1.3 && < 1.4
    - text >= 2.0 && < 2.1

  sd-jwt-interop-test:
    main:                InteropSpec.hs
    source-dirs:
    - test/interop
    - test
    other-modules:
    - TestCaseParser
    - TestCaseRunner
    - TestKeys
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
      condition: flag(interop-tests)
      then:
        dependencies:
        - sd-jwt
        - base >= 4.14 && < 5
        - hspec >= 2.10
        - aeson >= 2.0 && < 2.3
        - HsYAML >= 0.2 && < 0.3
        - HsYAML-aeson >= 0.2 && < 0.3
        - text >= 2.0 && < 2.1
        - filepath >= 1.4
        - directory >= 1.3
        - containers >= 0.6 && < 0.7
        buildable: True
      else:
        buildable: False

  sd-jwt-print-presentations:
    main:                PrintPresentations.hs
    source-dirs:
    - test/interop
    - test
    other-modules:
    - TestCaseParser
    - TestCaseRunner
    - TestKeys
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
      condition: flag(interop-tests)
      then:
        dependencies:
        - sd-jwt
        - base >= 4.14 && < 5
        - aeson >= 2.0 && < 2.3
        - aeson-pretty >= 0.8
        - HsYAML >= 0.2 && < 0.3
        - HsYAML-aeson >= 0.2 && < 0.3
        - text >= 2.0 && < 2.1
        - filepath >= 1.4
        - directory >= 1.3
        - containers >= 0.6 && < 0.7
        - bytestring >= 0.11 && < 0.12
        buildable: True
      else:
        buildable: False
